export const detailedPageData = [
    { 
      id:"frontend",
      partener:true,
      mainHeading:"Frontend Developer",
      description:"Step by step guide to becoming a modern frontend developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:123,
      aboutTopic:"What is Frontend Development?",
      answer:"Front-end development is the development of visual and interactive elements of a website that users interact with directly. It's a combination of HTML, CSS and JavaScript, where HTML provides the structure, CSS the styling and layout, and JavaScript the dynamic behaviour and interactivity.",
      question2:"What does a Frontend Developer do?",
      answer2:"As a front-end developer, you'll be responsible for creating the user interface of a website, to ensure it looks good and is easy to use, with great focus on design principles and user experience. You'll be working closely with designers, back-end developers, and project managers to make sure the final product meets the client's needs and provides the best possible experience for the end-users."
    },
    { 
      id:"backend",
      partener:true,
      mainHeading:"Backend Developer",
      description:"Step by step guide to becoming a modern backend developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:141,
      aboutTopic:"What is Backend Development?",
      answer:"Backend web development is the part of web development that deals with the server-side of a web application. This includes creating and managing the server-side logic, connecting the application to a database, creating server-side APIs, handling user authentication and authorization, and processing and responding to user requests. It often involves the use of programming languages such as Python, Java, Ruby, PHP, JavaScript (Node.js), and .NET languages.",
      question2:"What does a Backend Developer do?",
      answer2:"A backend developer is responsible for the development of server-side components of a web application i.e. working with databases, handling requests, creating server-side APIs that can be consumed by frontend developers to retrieve and manipulate data, ensuring the scalability of the systems i.e. making sure that the backend can handle a high volume of traffic and is performant, integrating external services like payment gateways, message queues, cloud services, etc."
    },
    { 
      id:"devops",
      partener:false,
      mainHeading:"DevOps Roadmap ",
      description:"Step by step guide for DevOps, SRE or any other Operations Role in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:133,
      aboutTopic:"What is DevOps?",
      answer:`DevOps is a cultural and collaborative mindset that emphasizes communication, collaboration, integration, and automation between development and operations teams in order to achieve faster and more reliable software delivery.
  
      DevOps is not a specific job title or role, but rather a set of practices and principles that can be applied across a variety of roles in software development and IT operations. Anyone involved in the software development and delivery process can adopt a DevOps mindset and apply DevOps practices in their work, including developers, testers, operations engineers, product managers, and others.`,
      question2:"What is a DevOps Engineer?",
      answer2:`While DevOps is not a specific job title or role, organizations often hire for a "DevOps Engineer" role. A DevOps Engineer is a software engineer who specializes in the practices and tools that enable the continuous delivery of software. DevOps Engineers are responsible for the design and implementation of applications, software, and services for their organization, and they work closely with developers, testers, and operations staff to oversee the code releases.`
    },
    { 
      id:"full-stack",
      partener:false,
      mainHeading:"Full Stack Developer",
      description:"Step by step guide to becoming a modern full stack developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:37,
      aboutTopic:"What is Full Stack Development?",
      answer:"Full stack development is the practice of being proficient in both the front-end and back-end aspects of web application development. A full stack developer is capable of working on all layers of a software application, from the user interface and user experience (front-end) to the server, database, and server-side logic (back-end). This versatility allows them to create and maintain complete web applications independently or as part of a development team.",
      question2:"",
      answer2:""
    },
    { 
      id:"android",
      partener:false,
      mainHeading:"Android Developer",
      description:"Step by step guide to becoming an Android developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:106,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"postgresql",
      partener:false,
      mainHeading:"PostgreSQL DBA",
      description:"Step by step guide to becoming a modern PostgreSQL DB Administrator in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:199,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"ai-and-data-scientist",
      partener:false,
      mainHeading:"AI and Data Scientist Roadmap",
      description:"Step by step guide to becoming an AI and Data Scientist in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:17,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"blockchain",
      partener:false,
      mainHeading:"Blockchain Developer",
      description:"Step by step guide to becoming a blockchain developer in 2023.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:119,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"qa",
      partener:false,
      mainHeading:"QA Engineer",
      description:"Steps to follow in order to become a modern QA Engineer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:144,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"software-architect",
      partener:false,
      mainHeading:"Software Architect ",
      description:"Step by step guide to becoming a Software Architect in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:107,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"asp.net-core",
      partener:false,
      mainHeading:"ASP.NET Core Developer",
      description:"Step by step guide to becoming an ASP.NET core developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:168,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
  
    { 
      id:"c++",
      partener:false,
      mainHeading:"C++ Developer Roadmap ",
      description:"Step by step guide to becoming a C++ developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:123,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"flutter",
      partener:false,
      mainHeading:"Flutter Developer",
      description:"Step by step guide to becoming a Flutter developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:108,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"cyber-security",
      partener:false,
      mainHeading:"Cyber Security Expert",
      description:"Step by step guide to becoming a Cyber Security Expert in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:308,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"ux-design",
      partener:false,
      mainHeading:"UX Design",
      description:"Step by step guide to becoming a UX Designer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:94,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"react-native",
      partener:false,
      mainHeading:"React Native Developer",
      description:"Step by step guide to becoming a React Native developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:96,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"game-developer",
      partener:false,
      mainHeading:"Game Developer",
      description:"Roadmap to becoming a Game Developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:145,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"technical-writer",
      partener:false,
      mainHeading:"Technical Writer",
      description:"Roadmap for anyone looking for a career in technical writing",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:84,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"computer-science",
      partener:false,
      mainHeading:"Computer Science",
      description:"Computer Science curriculum with free resources for a self-taught developer.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:197,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"react",
      partener:false,
      mainHeading:"React Developer",
      description:"Everything that is there to learn about React and the ecosystem in 2023.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:69,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"angular",
      partener:false,
      mainHeading:"Angular Developer",
      description:"Everything that is there to learn about Angular and the ecosystem in 2023.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:76,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"vue",
      partener:false,
      mainHeading:"Vue Developer",
      description:"Everything that is there to learn about Vue and the ecosystem in 2023.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:67,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"javascript",
      partener:false,
      mainHeading:"JavaScript Roadmap",
      description:"Step by step guide to learn JavaScript in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:118,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"node.js",
      partener:false,
      mainHeading:"Node.js Developer ",
      description:"Step by step guide to becoming a modern Node.js developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:117,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"typescript",
      partener:false,
      mainHeading:"TypeScript",
      description:"Everything you need to learn about TypeScript in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:94,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"python",
      partener:false,
      mainHeading:"Python Developer",
      description:"Step by step guide to becoming a Python developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:50,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"sql",
      partener:false,
      mainHeading:"SQL Roadmap",
      description:"Step by step guide to learning SQL in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:118,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"system-design",
      partener:false,
      mainHeading:"System Design",
      description:"Everything you need to know about designing large scale systems.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:151,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"java",
      partener:false,
      mainHeading:"Java Developer",
      description:"Step by step guide to becoming a Java developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:52,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"spring-boot",
      partener:false,
      mainHeading:"Spring Boot Developer",
      description:"Step by step guide to becoming a Spring Boot developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:48,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"go-roadmap",
      partener:false,
      mainHeading:"Go Developer",
      description:"Step by step guide to becoming a Go developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:67,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"rust",
      partener:false,
      mainHeading:"Rust Developer",
      description:"Step by step guide to becoming a Rust developer in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:125,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"graphql",
      partener:false,
      mainHeading:"GraphQL",
      description:"Step by step guide to learn GraphQL in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:63,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    { 
      id:"design-and-architecture",
      partener:false,
      mainHeading:"Software Design and Architecture",
      description:"Step by step guide to learn software design and architecture",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:95,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"design-system",
      partener:false,
      mainHeading:"Design System",
      description:"Learn how to create a design system with this step by step guide",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:124,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"code-review",
      partener:false,
      mainHeading:"Code Review Pyramid",
      description:"Learn what to focus on when conducting a code review.",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:5,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"docker",
      partener:false,
      mainHeading:"Docker Roadmap",
      description:"Step by step guide to learning Docker in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:51,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"kubernetes",
      partener:false,
      mainHeading:"Kubernetes Roadmap",
      description:"Step by step guide to learning Kubernetes in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:67,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"mongodb",
      partener:false,
      mainHeading:"MongoDB Roadmap",
      description:"Step by step guide to learning MongoDB in 2023",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:116,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"prompt-engineering",
      partener:false,
      mainHeading:"Prompt Engineering Roadmap",
      description:"Step by step guide to learning Prompt Engineering",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:59,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"frontend-performance",
      partener:false,
      mainHeading:"Frontend Performance Best Practices",
      description:"Detailed list of best practices to improve your frontend performance",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:48,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"api-security",
      partener:false,
      mainHeading:"API Security Best Practices",
      description:"Detailed list of best practices to make your APIs secure",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:51,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"aws",
      partener:false,
      mainHeading:"AWS Best Practices",
      description:"Detailed list of best practices for Amazon Web Services (AWS)",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:49,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    }, { 
      id:"code-reviews",
      partener:false,
      mainHeading:"Code Review Best Practices",
      description:"Detailed list of best practices for effective code reviews and quality",
      done:"0%",
      complete:0,
      progress:0,
      skip:0,
      total:70,
      aboutTopic:"",
      answer:"",
      question2:"",
      answer2:""
    },
    //  { 
    //   id:"javascript-questions",
    //   partener:false,
    //   mainHeading:"",
    //   description:"",
    //   done:"0%",
    //   complete:0,
    //   progress:0,
    //   skip:0,
    //   total:,
    //   aboutTopic:"",
    //   answer:"",
    //   question2:"",
    //   answer2:""
    // }, { 
    //   id:"react-questions",
    //   partener:false,
    //   mainHeading:"",
    //   description:"",
    //   done:"0%",
    //   complete:0,
    //   progress:0,
    //   skip:0,
    //   total:,
    //   aboutTopic:"",
    //   answer:"",
    //   question2:"",
    //   answer2:""
    // },
  ]