export const vdoData = [
    {
      id: "session-based-authentication",
      topic: "Session Based Authentication",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/gKkBEOq_shs",
    },
    {
      id: "basics-of-authentication",
      topic: "Basic Authentication",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/mwccHwUn7Gc",
    },
    {
      id: "heap-data-structure",
      topic: "Heap Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/F_r0sJ1RqWk",
    },
    {
      id: "tree-data-structure",
      topic: "Tree Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/S2W3SXGPVyU",
    }, {
      id: "hash-table-data-structure",
      topic: "Hash Table Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/jalSiaIi8j4",
    },
    {
      id: "queue-data-structure",
      topic: "Queue Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/mDCi1lXd9hc",
    },
    {
      id: "stack-data-structure",
      topic: "Stack Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/I5lq6sCuABE",
    },
    {
      id: "linked-list-data-structure",
      topic: "Linked List Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/odW9FU8jPRQ",
    },
    {
      id: "all-about-array-data-structure",
      topic: "All about Array Data Structure",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/QJNwK2uJyGs",
    },

    {
      id: "what-is-eventual-consistency",
      topic: "What is Eventual Consistency?",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/rpqsSkTIdAw",
    },
    {
      id: "ssh-vs-tls-vs-ssl",
      topic: "SSH vs TLS vs SSL",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/k3rFFLmQCuY",
    },
    {
      id: "asynchronous-javascript",
      topic: "Asynchronous JavaScript",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/VyIK6SV5f7o",
    },
    {
      id: "random-number-generators",
      topic: "Random Number Generators",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/nDv3yXdD0rk",
    },
    {
      id: "big-o-notation",
      topic: "Big O Notation",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/Z0bH0cMY0E8",
    }, {
      id: "yaml-in-depth",
      topic: "YAML in Depth",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/ImHSpwUlNVc",
    },
    {
      id: "floating-point-arithmetic",
      topic: "Floating Point Arithmetic",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/RIiq4tTt6rI",
    },
    {
      id: "what-is-cap-theorem",
      topic: "What is CAP Theorem?",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/_RbsFXWRZ10",
    },
    {
      id: "acid-explained",
      topic: "ACID Explained",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/yaQ5YMWkxq4",
    },
    {
      id: "tcp-ip-model-explained",
      topic: "TCP/IP Model Explained",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/F5rni9fr1yE",
    },
    {
      id: "osi-model-explained",
      topic: "OSI Model Explained",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/dV8mjZd1OtU",
    },
    {
      id: "freeze-and-seal-in-javascript",
      topic: "Freeze and Seal in JavaScript",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/O3uT2l6vgZ8",
    },
    {
      id: "all-about-http-caching",
      topic: "All about HTTP Caching",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/HiBDZgTNpXY",
    },
    {
      id: "content-delivery-networks",
      topic: "Content Delivery Networks",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/6DXEPcXKQNY",
    },
    {
      id: "load-balancers-101",
      topic: "Load Balancers 101",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/galcDRNd5Ow",
    },
    {
      id: "dns-records",
      topic: "DNS Records",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/7lxgpKh_fRY",
    }, {
      id: "dns-and-how-does-it-work",
      topic: "DNS and how does it work?",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/Wj0od2ag5sk",
    },
    {
      id: "system-design-101",
      topic: "System Design 101",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/Y-Gl4HEyeUQ",
    },
    {
      id: "javascript-fetch-api",
      topic: "JavaScript Fetch API",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/-ZI0ea5O2oA",
    },
    {
      id: "scaling-the-unscalable",
      topic: "Scaling the Unscalable",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/a2rcgzludDU",
    },
    {
      id: "all-about-promises-in-javascript",
      topic: "All about Promises in JavaScript",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/BvrkobaCVVE",
    },
    {
      id: "dom,-shadow-dom,-virtual-dom",
      topic: "DOM, Shadow DOM, Virtual DOM",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/7Tok22qxPzQ",
    },
    {
      id: "automate-with-github-actions",
      topic: "Automate with GitHub Actions",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/nyKZTKQS_EQ",
    },
    {
      id: "practical-introduction-to-react",
      topic: "Practical Introduction to React",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/NyG7YJWJd6s",
    },
    {
      id: "what-is-dependency-injection",
      topic: "What is Dependency Injection?",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/0yc2UANSDiw",
    },
    {
      id: "how-to-use-css-variables",
      topic: "How to use CSS Variables?",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/lgaxU7CRmxU",
    },
    {
      id: "arrays-and-objects-in-javascript",
      topic: "Arrays and Objects in JavaScript",
      description: "Learn everything you need to know about session authentication",
      vdoLink: "https://www.youtube.com/embed/n3NKGsM3iEw",
    },
    {
      id: "graph-data-structure",
      topic: "Graph Data Structure",
      description: "Learn everything you need to know about the graph data structure",
      vdoLink: "https://www.youtube.com/embed/0sQE8zKhad0",
    },
    {
      id: "basic-authentication",
      topic: "Basic Authentication",
      description: "Learn everything you need to know about basic authentication",
      vdoLink: "https://www.youtube.com/embed/mwccHwUn7Gc",
    },
    {
      id: "all-about-array-data-structure",
      topic: "Basic Authentication",
      description: "Learn everything you need to know about basic authentication",
      vdoLink: "https://www.youtube.com/embed/mwccHwUn7Gc",
    },
    {
      id: "what-are-data-structures",
      topic: "What are Data Structures?",
      description: "Learn about the different data structures in this illustrated series",
      vdoLink: "https://www.youtube.com/embed/9rhT3P1MDHk",
    },
    {
      id: "transport-protocols:-tcp-vs-udp",
      topic: "Transport Protocols: TCP vs UDP",
      description: "Learn about the Transport Layer of the TCP/IP model and different transport protocols.",
      vdoLink: "https://www.youtube.com/embed/37AFBZv4_6Y",
    },
  ];